article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import path,include
#şuanki klasör
app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard,name = "dashboard"),
    path('addarticle/', views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name ="detail"),
    path('update/<int:id>',views.update,name ="update"),
    path('delete/<int:id>',views.deleteArticle,name ="delete"),
    path('',views.articles,name ="articles"),
    path('comment/<int:id>',views.addComment,name ="comment"),
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('dashboard',views.dashboard,name = "dashboard"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    #article görülürse articles.urlse bak
    path('user/',include("user.urls")),
    #user/register veya login veya logoutta user.urlse git
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register,name = "register"),
    path('login/', views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name = "Yazar")
    #User silinirse o usera ait articleler silinmiş olacak
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin.")#hem boş olabilir hem dolu
    #Otomatik ekle auto_now_add
    #Özel bir metod
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name ="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['comment_date']#sıralama yapılır

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import requests
import json
from django.urls import reverse
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")
    keyword2 = request.GET.get("keyword2")

    if keyword and keyword2:
            print("sa")
            articles =Article.objects.filter(id__contains = keyword2,title__contains = keyword)
            messages.success(request,"Id ve Cihaz ismine ait cihazlar görüntüleniyor.")
            return render(request,"articles.html",{"articles":articles})

    messages.warning(request,"Bulunamadı.Lütfen Cihaz id'sini ve ismini doğru girdiğinizden emin olun.")

    return render(request,"articles.html")

def index(request):
    context = {
        "numbers":[1,2,3,4,5]
    }
    return render(request,"index.html",context)

def dashboard():
    context = {
        "numbers":[1,2,3,4,5]
    }
    return render(request,"dashboard.html",context)

def about(request):
    return render(request,"about.html")
@login_required(login_url = "user:login")
def dashboard(request):
    articles =Article.objects.all()
    context = {
        "articles":articles
    }

    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        """
        article objesini oluşturuyor.
        bizim articleyi oluştur ama save yapma onu ben yapıcam demek lazım
        article.save() yapıyor
        """
        messages.success(request,"Makale başarıyla oluşturuldu.")
        return redirect("dashboard")

    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article =  get_object_or_404(Article,id = id)

    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url = "user:login")
def update(request,id):

    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        """
        article objesini oluşturuyor.
        bizim articleyi oluştur ama save yapma onu ben yapıcam demek lazım
        article.save() yapıyor
        """
        messages.success(request,"Makale başarıyla güncellendi.")
        return redirect("dashboard")
    
    return render(request,"update.html",{"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("dashboard")
def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author = comment_author,comment_content = comment_content)

        newComment.article = article

        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))#Dinamik url yapısı reverse fonksiyonuyla daha iyi olur

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3>Hakkımızda</h3>
<hr>

<p>
    Merhaba
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout2.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">
        <div class="col-md-6 offset-md-3">
                <h3>Makale Oluştur</h3>
                <hr>
                <form method = "post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.media }}
                        {{form|crispy}}
                        <br>
                        <button type = "submit" class = "btn btn-danger">Makale ekle</button>
                    
                    </form>
                    
        </div>
      </div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<br><br><br><br><br><br><br><br>
{% if messages %}
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endif %}
                   
                    {% endfor %}
    {% endif %}
<div class="row">
    <div class="col-md-10 offset-md-3">
      <div class="col-lg-8">
        <h3>Cihazlar</h3>
        <h6>Lütfen cihaz id'sini ve Cihaz ismini birlikte girerek arama yapın.</h6>
        <hr>
      </div>
    </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
      <div class="col-lg-8">
        <form>
        {% csrf_token %}
          <input type="text" name = "keyword" class="  search-query " placeholder="Cihaz ismi">
          <input type="text" name = "keyword2" class="  search-query " placeholder="Cihaz id'si">
          <button type="submit" class="btn btn-danger">Ara</button>
            
        </form>
      </div>
    </div>
</div>
{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <!-- Post Content Column -->
        <div class="col-lg-8">
  
          <!-- Title -->
          <a href="{% url 'article:detail' article.id %}" ><h2 class="mt-4">{{article.title}}</h2></a>
  
          <!-- Author -->
          <p class="lead">
            by
            {{article.author.username}}
          </p>
  
          <hr>
  
          <!-- Date/Time -->
          <p>{{article.created_date}}</p>
  
          <hr>
          <p class="lead">
              {{article.content|safe|truncatewords:10}}<!-- html içerikler normal içeriğe dönüşsün -->
          </p>
          <a style ="float : right;"href ="{% url 'article:detail' article.id %}" class = "btn btn-danger">Devamını Oku</a>
          <hr>
          <!-- Preview Image -->
          {% if article.article_image%}
           <a href="{% url 'article:detail' article.id %}" ><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
          {% else %}

          {% endif %}
  
          <hr>
      </div>
    </div>
</div>

{% endfor %}

{% else %}
<div class ="row">
    <div class="col-md-10 offset-md-3">
      <div class="col-lg-8">
        <div class ="alert alert-danger">
           Cihaz bulunamadı.Doğru girdiğinizden emin olun.
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout2.html" %}

{% block body %}
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Girdi ekle</a>
<hr>
<!-- DOM dataTable -->
<div class="col-md-12">
    <div class="widget">
        <header class="widget-header">
            <h4 class="widget-title">Default DataTable</h4>
        </header><!-- .widget-header -->
        <hr class="widget-separator">
        <div class="widget-body">
            <div class="table-responsive">
                {% if articles %}
                
                <table id="default-datatable" data-plugin="DataTable" class="table table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Başlık</th>
                            <th scope="col">Yazar</th>
                            <th scope="col">Tarih</th>
                            <th scope="col">Güncelle</th>
                            <th scope="col">Sil</th>
                        </tr>
                    </thead>
                    <tfoot>
                        
                    </tfoot>
                    <tbody>
                        {% for article in articles %}
                        <tr>       
                            <th scope="row">{{article.id}}</th>
                            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                            <td>{{article.author.username}}</td>
                            <td>{{article.created_date}}</td>
                            {%if article.author.username in request.user.username %}
                            <td><a href="{% url 'article:update' article.id %}"class = "btn btn-danger">Güncelle</a></td>
                            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil</a></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
            <div class = "alert alert-danger">
                    Henüz Bir girdiniz bulunmuyor..
                
            </div>
            {% endif %}
            </div>
        </div><!-- .widget-body -->
    </div><!-- .widget -->
</div><!-- END column -->


{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<br><br><br><br><br><br><br><br>
<div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
  
          <!-- Title -->
          <h2 class="mt-4">{{article.title}}</h2>
  
          <!-- Author -->
          <p class="lead">
            by
            {{article.author.username}}
          </p>
  
          <hr>
  
          <!-- Date/Time -->
          <p> Oluşturulma tarihi:{{article.created_date}}</p>
  
          <hr>
          <p class="lead">
              <h2>Cihaz açıklaması :</h2> {{article.content|safe}}<!-- html içerikler normal içeriğe dönüşsün -->
          </p>
          <!-- Preview Image -->
          {% if article.article_image%}
           <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
          {% else %}

          {% endif %}
  
          <hr>
          
          <h4>Yorumlar</h4>
          <hr>
          {% if comments %}

          {% for comment in comments %}
            <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.comment_author}}</h5>
              {{comment.comment_date}}<br>
              {{comment.comment_content}}
            </div>
          </div>
          {% endfor %}

          {% else %}
          <div class="alert alert-danger">
          Bu makaleye herhangi bir yorum yazılmamış,İlk yorum yapan siz olun.
          </div>
          {% endif %}

          <div class="card my-4">
            <h5 class="card-header">Yorum Ekle:</h5>
            <div class="card-body">
              <form method="post" action = "{% url 'article:comment' article.id %}" >
              {% csrf_token %}
                <div class="form-group">
                <label for="formGroupExampleInput">İsim</label>
                <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin.">
                </div>
                <div class="form-group">
                  <label for="formGroupExampleInput">Yorum</label>
                  <textarea name ="comment_content" class="form-control" rows="3"></textarea>                 
                </div>
                <button type="submit" class="btn btn-danger">Ekle</button>
              </form>
            </div>
          </div>
 </div>    

{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block body %}

        <div class="wrapper">
          
          <header id="header">
            <div class="container">
                
              <div class="row">
                <div class="col-md-10 col-md-offset-1">
                  <div class="intro-text">
                    
                    <h2 class="section-heading animated">Sorunlarınız bizimle çözüm bulsun</h2>
                    <p class="section-paragraph">Notebook tamirinde rakipsiz<br>Profesyonel kadromuzla sıfırdan bilgisayar bile üretebiliriz
                    <br>(Mustafa Özdal,Ömer Özdal)
                      </p>
                      {% if request.user.is_authenticated %}
                        <p>Hoşgeldin {{request.user.username}}. Günün güzel geçsin!</p>
                      {% else %}
                        <p>Giriş Yapılmamış</p>
                      {% endif %}
                  </div>
                   <a class = "btn btn-block btn-info" href = "{% url 'article:articles' %}">Tıkla ve cihazının durumunu öğren.</a>
        
                </div> 
               
              </div>

              
            </div><!-- .container -->
          </header><!-- #header -->

      
        
          <section id="features">
            <div class="container">
      
              <div class="text-center">
                <h2 class="section-heading animated">İstediğiniz bilgisayar sorunlarınıza tamir çözümü burada</h2>
                <p class="section-paragraph">Deneyimli çalışan kadromuz ile Büyükçekmecede müşterilerimizi bekliyoruz.</p>
              </div><!-- .text-center -->
      
              <div class="row text-center">
      
                <div class="col-md-4">
                  <div class="col-inner feature">
                    <img src="{% static 'assets/svg/tie.svg' %}" alt="icon">
                    <h4>Tecrübeli kadro</h4>
                    <p>Bulduğumuz yöntemlere siz bile şaşacaksınız!.</p>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-4">
                  <div class="col-inner feature">
                    <img src="{% static 'assets/svg/pig.svg' %}" alt="icon">
                    <h4>Ucuz tamir ücreti</h4>
                    <p>Sizi ve cebinizi düşünen bir patron.</p>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-4">
                  <div class="col-inner feature">
                    <img src="{% static 'assets/svg/pointer.svg' %}" alt="icon">
                    <h4>Tek tıkla hizmet</h4>
                    <p>Neredeyse tek tıkla hizmet!(Belki bi kaç tık fazla)</p>
                  </div>
                </div><!-- /.col -->
                
              </div><!-- .row -->
            </div><!-- .container -->
          </section><!-- #features -->
      
          <section id="brief">
            <div id="brief-img">
              <img src="{% static 'assets/images/landing-page/img-1.jpg' %}" alt="">
            </div><!-- #brief-img -->
      
            <div class="container">
              <div id="brief-text">
                <h2 class="section-heading animated">Yaratıcı &amp; Profesyonel </h2>
                <p class="section-paragraph">Çözümlerimiz alışılmışın dışında..</p>
                <ul>
                  <li>
                    <img class="item-icon" src="{% static 'assets/svg/check.svg' %}" alt="">
                    <span class="item-text">Yaratıcı</span>
                  </li>
                  <li>
                    <img class="item-icon" src="{% static 'assets/svg/check.svg' %}" alt="">
                    <span class="item-text">Tecrübeli</span>
                  </li>
                  <li>
                    <img class="item-icon" src="{% static 'assets/svg/check.svg' %}" alt="">
                    <span class="item-text">Bilgin</span>
                  </li>
                </ul>
              </div><!-- #brief-text -->
            </div><!-- .container -->
          </section><!-- #brief -->
      
          <section id="states" class="bg-primary">
            <div class="container">
              <div class="row">
                <div class="col-md-3 col-sm-6">
                  <div class="col-inner text-center">
                    <h3 class="counterUp">10</h3>
                    <h4>Avantajlarımız</h4>
                    <p>Çözemeyeceğimiz sorun sorun değildir.</p>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-3 col-sm-6">
                  <div class="col-inner text-center">
                    <h3 class="counterUp">30</h3>
                    <h4>Aktif Müşterilerimiz</h4>
                    <p>Çok yakında..</p>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-3 col-sm-6">
                  <div class="col-inner text-center">
                    <h3 class="counterUp">200</h3>
                    <h4>Tamir ettiğimiz işlemci arızaları</h4>
                    <p>İntel'den daha deneyimliyiz</p>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-3 col-sm-6">
                  <div class="col-inner text-center">
                    <h3 class="counterUp"></h3>
                      <h4></h4>
                  </div>
                </div><!-- /.col -->
              </div><!-- .row -->
            </div><!-- .container -->
          </section><!-- #states -->
      
          <section id="subscribe">
            <div class="container">
              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <div class="text-center">
                    <h2 class="section-heading animated">Üye olun</h2>
                    <p class="section-paragraph">Avantajlarımızdan haberdar olun</p>
                  </div>
                </div><!-- /.col -->
              </div><!-- .row -->
      
              <div class="subs-form">
                <form action="#" class="form-horizontal">
                  <div class="col-md-4">
                    <div class="control-wrap">
                      <input type="text" class="form-control" placeholder="Your Name">
                      <img src="{% static 'assets/images/landing-page/users.svg' %}" alt="">
                      
                    </div>
                  </div><!-- /.col -->
      
                  <div class="col-md-4">
                    <div class="control-wrap">
                      <input type="text" class="form-control" placeholder="Your Email">
                      <img src="{% static 'assets/images/landing-page/email.svg' %}" alt="">
                      
                    </div>
                  </div><!-- /.col -->
      
                  <div class="col-md-4">
                      <a class = "btn btn-block btn-primary" href = "{% url 'user:register' %}">Kayıt Ol!</a>
                  </div><!-- /.col -->
                </form>
              </div>
            </div><!-- .container -->
          </section><!-- #subscribe -->
      
          <section id="price">
            <div class="container">
              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <div class="text-center">
                    <h2 class="section-heading animated">Ücretlerimiz</h2>
                    <p class="section-paragraph">Sudan biraz daha pahalı</p>
                  </div>
                </div><!-- /.col -->
              </div><!-- .row -->
      
              <div class="row">
                <div class="col-md-4 price-column">
                  <div class="price-column-inner">
                    <header>
                      <h4>Arıza tespiti</h4>
                      <h3>Bedava</h3>
                    </header>
                    
                    <footer class="text-center">
                      <button class="btn btn-default">Bilgi al</button>
                    </footer>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-4 price-column">
                  <div class="price-column-inner">
                    <header>
                      <h4>Sıvı temaslı cihazlar</h4>
                      <h3>₺<span class="counterUp">150</span></h3>
                    </header>
                    
                    <footer class="text-center">
                      <button class="btn btn-primary">Bilgi al</button>
                    </footer>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-4 price-column">
                  <div class="price-column-inner">
                    <header>
                      <h4>Ana kart değişimleri</h4>
                      <h3>₺<span class="counterUp">415</span></h3>
                    </header>
                    
                    <footer class="text-center">
                      <button class="btn btn-default">Bilgi al</button>
                    </footer>
                  </div>
                </div><!-- /.col -->
              </div><!-- .row -->
            </div><!-- .container -->
          </section><!-- #price -->
         
          
          <section id="footer">
            <div class="container">
              <div class="row">
                <div class="col-md-2">
                  <div class="col-inner navigation">
                    <h2>NAVIGASYON</h2>
                    <ul class="navigation-menu">
                      <li><a href="#">HAKKIMIZDA</a></li>
                    </ul>
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-5 col-md-offset-1">
                  <div class="col-inner news">
                    <h2>YENİLİKLER</h2>
                    
                  </div>
                </div><!-- /.col -->
      
                <div class="col-md-3 col-md-offset-1">
                  <div class="col-inner">
                    
                  </div>
                </div><!-- /.col -->
              </div><!-- .row -->
            </div><!-- .container -->
          </section><!-- #footer -->
      
          <section id="copyright">
            <div class="container text-center">
              <p>Copyright &copy;tarafından yapılmıştır<a href="#" class="text-primary"> Eyup Can Doğan</a></p>
            </div>
          </section><!-- #copyright -->
        </div>
        <div id="loading-div">
          <img src="{% static 'assets/images/landing-page/puff.svg' %}" width="50" alt="">
        </div>
        
{% endblock body %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Bilgisayar Atölyesi-Login</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
	<meta name="description" content="Admin, Dashboard, Bootstrap" />
	<link rel="stylesheet" href ="{% static 'assets/images/logo.png' %}">
	<link rel="stylesheet" href ="{% static 'libs/bower/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href ="{% static 'libs/bower/material-design-iconic-font/dist/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" href ="{% static 'libs/bower/animate.css/animate.min.css' %}">
	<link rel="stylesheet" href ="{% static 'assets/css/bootstrap.css' %}">
	<link rel="stylesheet" href ="{% static 'assets/css/core.css' %}">
	<link rel="stylesheet" href ="{% static 'assets/css/misc-pages.css' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800,900,300">
</head>
<body class="simple-page">
	<div id="back-to-home">
		<a href="{% url 'index' %}" class="btn btn-outline btn-default"><i class="fa fa-home animated zoomIn"></i></a>
	</div>
	
	<div class="simple-page-wrap">
		<div class="simple-page-logo animated swing">
			<a href="{% url 'index' %}">
				<span><i class="fa fa-gg"></i></span>
				<span>Bilgisayar Atölyesi</span>
			</a>
		</div><!-- logo -->
		<div class="simple-page-form animated flipInY" id="login-form">
	<h4 class="form-title m-b-xl text-center">Giriş yapın</h4>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		
		<div class="form-group m-b-xl">
			<div class="checkbox checkbox-primary">
				<input type="checkbox" id="keep_me_logged_in"/>
				<label for="keep_me_logged_in">Unutma sorucam</label>
			</div>
		</div>
		<input type="submit" class="btn btn-primary" value="Giriş">
	</form>
</div><!-- #login-form -->

<div class="simple-page-footer">
	<p>
		<small>Hesabınız yokmu ?</small>
		<a href="{% url 'user:register' %}">Oluştur</a>
	</p>
</div><!-- .simple-page-footer -->
{% if messages %}
{% for message in messages %}
{% if message.tags == "info" %}
<div class="alert alert-danger">{{ message }}</div>
{% else %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endif %}

{% endfor %}
{% endif %}

	</div><!-- .simple-page-wrap -->
</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Infinity - Bootstrap Admin Template</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
	<meta name="description" content="Admin, Dashboard, Bootstrap" />
	<link rel="stylesheet" href ="{% static 'assets/images/logo.png' %}">
	<link rel="stylesheet" href ="{% static 'libs/bower/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href ="{% static 'libs/bower/material-design-iconic-font/dist/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" href ="{% static 'libs/bower/animate.css/animate.min.css' %}">
	<link rel="stylesheet" href ="{% static 'assets/css/bootstrap.css' %}">
	<link rel="stylesheet" href ="{% static 'assets/css/core.css' %}">
	<link rel="stylesheet" href ="{% static 'assets/css/misc-pages.css' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800,900,300">
</head>
<body class="simple-page">
	<div id="back-to-home">
		<a href="{% url 'index' %}" class="btn btn-outline btn-default"><i class="fa fa-home animated zoomIn"></i></a>
	</div>
	<div class="simple-page-wrap">
		<div class="simple-page-logo animated swing">
			<a href="{% url 'index' %}">
				<span><i class="fa fa-gg"></i></span>
				<span>Bilgisayar Atölyesi</span>
			</a>
		</div><!-- logo -->
		
<div class="simple-page-form animated flipInY" id="signup-form">
	<h4 class="form-title m-b-xl text-center">Kayıt ol</h4>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}

		<div class="form-group m-b-xl">
			<div class="checkbox checkbox-primary">
				
			</div>
		</div>
		<input type="submit" class="btn btn-primary" value="Kayıt ol">
	</form>
</div><!-- #login-form -->

<div class="simple-page-footer">
	<p>
		<small>Hesabın var mı?</small>
		<a href="{% url 'user:login' %}">Giriş yap</a>
	</p>
</div><!-- .simple-page-footer -->
{% if messages %}
{% for message in messages %}
{% if message.tags == "info" %}
<div class="alert alert-danger">{{ message }}</div>
{% else %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endif %}

{% endfor %}
{% endif %}

	</div><!-- .simple-page-wrap -->
</body>
</html>

templates/update.html
{% extends "layout2.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">
        <div class="col-md-6 offset-md-3">
                <h3>Makale Güncelle</h3>
                <hr>
                <form method = "post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.media }}
                        {{form|crispy}}
                        <br>
                        <button type = "submit" class = "btn btn-danger">Makale Güncelle</button>
                    
                    </form>
                    
        </div>
      </div>


{% endblock body %}